spring:
  profiles: local
  #datasource-configuration
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=true
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=true
    initial
    driver-class-name: org.h2.Driver
    username: root
    password: 1367
  #hibernate-configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        format_sql: true
        show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
#logging-configuration
logging:
  level:
    org.hibernate.type: trace
server:
  port: 8282