
INSERT INTO tb_record_type VALUES(1,'out');
INSERT INTO tb_record_type VALUES(2,'saving');

INSERT INTO PUBLIC.TB_RECORD (MEMBER_NAME, PRICE, RECORD_DATE, FK_RECORD_TYPE) VALUES ('Anto', 1000, '2019-11-12', 1);
INSERT INTO PUBLIC.TB_RECORD (MEMBER_NAME, PRICE, RECORD_DATE, FK_RECORD_TYPE) VALUES ('DU', 1300, '2019-11-11', 2);
INSERT INTO PUBLIC.TB_RECORD (MEMBER_NAME, PRICE, RECORD_DATE, FK_RECORD_TYPE) VALUES ('HK', 200, '2019-11-02', 2);
INSERT INTO PUBLIC.TB_RECORD (MEMBER_NAME, PRICE, RECORD_DATE, FK_RECORD_TYPE) VALUES ('JS', 100-00, '2019-11-13', 1);