spring:
  thymeleaf:
    cache: false
    enabled: true

  ### Database ###
  datasource:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=true
    username: root
    password: 1367
    validation-query: SELECT 1
    continue-on-error: true
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=true
  h2:
    console:
      enabled: true
      path: /h2-console
  ### JPA ###
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration/${spring.profiles.active}

### logging - hibernate ###
logging:
  level:
    org:
      hibernate:
        sql: trace
        type:
          descriptor:
            sql: trace






