spring:
  ### Database ###
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 1367
    validation-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console
  ### JPA ###
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

### logging - hibernate ###
logging:
  level:
    org:
      hibernate:
        sql: debug
      type:
        descriptor:
          sql: trace
