spring:
  ### Database ###
  datasource:
    url: jdbc:mysql://localhost:3306/dailyIssue?serverTimezone=UTC
    username: root
    password: password
    validation-query: SELECT 1
  ### JPA ###
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/${spring.profiles.active}


### logging - hibernate ###
logging:
  level:
    org:
      hibernate:
        sql: trace
        type:
          descriptor:
            sql: trace
