spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
#      ddl-auto: validate
      show-sql: true
    # cuz auto-detecting
    #database: MYSQL
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: 1367
    validation-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console